=== titalvi/QTVocabTrainer/profiles/profile.dtd
<!ELEMENT profile (username,termbase)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT termbase (entry+)>
<!ELEMENT entry (term+,comment,confidence-score)>
<!ELEMENT term (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT confidence-score (#PCDATA)>


<!ATTLIST termbase lang-pair CDATA #REQUIRED>
<!ATTLIST term lang CDATA #REQUIRED>
<!ATTLIST entry id CDATA #REQUIRED>

=== titalvi/QTVocabTrainer/profiles/testprofile.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE profile SYSTEM "profile.dtd">
<profile>
    <username>testprofile</username>
    <termbase lang-pair="de-en">
        <entry id="1">
            <term lang="de">schlafen</term>
            <term lang="en">sleep</term>
            <comment>verb</comment>
            <confidence-score>0.0</confidence-score>
        </entry>
        <entry id="2">
            <term lang="de">w√§hlen</term>
            <term lang="en">elect</term>
            <comment>Context: politics</comment>
            <confidence-score>0.0</confidence-score>
        </entry>
        <entry id="3">
            <term lang="de">Bett</term>
            <term lang="en">bed</term>
            <comment></comment>
            <confidence-score>0.0</confidence-score>
        </entry>
        <entry id="4">
            <term lang="de">Dusche</term>
            <term lang="en">shower</term>
            <comment>noun</comment>
            <confidence-score>0.0</confidence-score>
        </entry>
    </termbase>
</profile>
